"""Generates docs/ACTION-UNLOCKS.md: every action, the era that unlocks it, and the mechanics that gate it beyond the era (2026-10-05).

Why: the same class of bug kept turning up (an action listed in an era that nothing lets a tribe reach, a menu lock that forgot a later
action), and the only way to see what a tribe can do and why was to read four files. This reads them for you and prints one table per era.

What it reads, all from the code, so a re-run after any change stays true:
  - eras.ERAS: the era that lists the action (config.DISABLED_ACTIONS are marked off).
  - simulation.AFFORDABILITY_CHECKS: the flat gate a menu entry must pass (cost, a built flag, a free footprint).
  - simulation.ONE_TIME_BUILD_FLAGS: the flag that retires a one-time action from the menu.
  - the handler in actions.ACTION_REGISTRY: its guard clauses (an early `if ...: return None` or return of a message), the real prerequisites.
  - simulation.Simulation._prepare_turn: the line numbers where the action is named in a menu filter, for the rules that do not fit a table.
  - the named menu sets (pre-settlement, survival crisis, rival-dependent, endgame resolution, vessel standing).

    python scripts/action_unlocks.py            (rewrites docs/ACTION-UNLOCKS.md)
"""
import ast
import re
import sys
import textwrap

sys.path.insert(0, ".")

from backend import config, simulation
from backend.actions import ACTION_REGISTRY
from backend.eras import ERAS

OUT = "docs/ACTION-UNLOCKS.md"
SIM_SRC = open("backend/simulation.py", encoding="utf-8").read()
ACT_SRC = open("backend/actions.py", encoding="utf-8").read()
SIM_TREE = ast.parse(SIM_SRC)
ACT_TREE = ast.parse(ACT_SRC)


def squash(text: str, limit: int = 150) -> str:
    text = re.sub(r"\s+", " ", text).strip().replace("|", "/")
    return text if len(text) <= limit else text[: limit - 1] + "..."


def dict_literal(tree, src, name):
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign) and any(isinstance(t, ast.Name) and t.id == name for t in node.targets) and isinstance(node.value, ast.Dict):
            return {ast.literal_eval(k): v for k, v in zip(node.value.keys, node.value.values) if isinstance(k, ast.Constant)}
        if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name) and node.target.id == name and isinstance(node.value, ast.Dict):
            return {ast.literal_eval(k): v for k, v in zip(node.value.keys, node.value.values) if isinstance(k, ast.Constant)}
    return {}


afford_nodes = dict_literal(SIM_TREE, SIM_SRC, "AFFORDABILITY_CHECKS")
afford = {}
for action, node in afford_nodes.items():
    body = node.body if isinstance(node, ast.Lambda) else node
    afford[action] = squash(ast.get_source_segment(SIM_SRC, body) or "")
one_time = {k: ast.literal_eval(v) for k, v in dict_literal(SIM_TREE, SIM_SRC, "ONE_TIME_BUILD_FLAGS").items()}

# guard clauses of each handler
funcs = {n.name: n for n in ast.walk(ACT_TREE) if isinstance(n, ast.FunctionDef)}


def guards(action):
    handler = ACTION_REGISTRY.get(action)
    node = funcs.get(getattr(handler, "__name__", ""))
    if node is None:
        return []
    found = []
    for stmt in node.body:
        if isinstance(stmt, ast.If) and len(stmt.body) == 1 and isinstance(stmt.body[0], ast.Return):
            value = stmt.body[0].value
            if value is None or (isinstance(value, ast.Constant) and (value.value is None or isinstance(value.value, str))):
                test = ast.get_source_segment(ACT_SRC, stmt.test) or ""
                found.append(squash(test, 110))
    return found[:4]


# lines of _prepare_turn that name an action inside a filter
prep = next(n for n in ast.walk(SIM_TREE) if isinstance(n, ast.FunctionDef) and n.name == "_prepare_turn")
filter_lines = {}
for node in ast.walk(prep):
    if isinstance(node, (ast.ListComp, ast.Compare)):
        for const in ast.walk(node):
            if isinstance(const, ast.Constant) and isinstance(const.value, str) and const.value in ACTION_REGISTRY:
                filter_lines.setdefault(const.value, set()).add(const.lineno)

named_sets = {
    "pre-settlement menu": set(config.PRE_SETTLEMENT_ACTIONS),
    "survival crisis menu": set(simulation.SURVIVAL_CRISIS_ACTIONS),
    "needs a living rival": set(simulation.RIVAL_DEPENDENT_ACTIONS),
    "final-era lock (rival alive)": set(simulation.ENDGAME_RESOLUTION_ACTIONS),
    "once the vessel stands": set(simulation.VESSEL_STANDING_ACTIONS),
}

lines = ["# What is unlocked, and how", "",
         "Generated by `scripts/action_unlocks.py` from the code on every run (do not edit by hand). Each action appears under the era that lists it. "
         "\"Free with the era\" means nothing beyond the era gates it (the action is always on the menu once the era arrives and the tribe has the plain "
         "wood, stone or food it costs). Everything else is a gate. Era gates themselves are in `backend/eras.py` (`requires_population`, `requires_ready`, "
         "the 50-cycle floor).", ""]
lines += ["## The eras", "", "| # | Era | Population line | Must have built or mastered | Unlocks |", "|---|---|---|---|---|"]
for i, era in enumerate(ERAS):
    ready = ", ".join(era.requires_ready) or "nothing"
    n = len([a for a in era.unlocks_actions if a not in config.DISABLED_ACTIONS])
    lines.append(f"| {i} | {era.label} | {era.requires_population:,} | {ready} | {n} actions |")
lines.append("")
cumulative = set()
sizes = []
for era in ERAS:
    cumulative |= {a for a in era.unlocks_actions if a not in config.DISABLED_ACTIONS}
    sizes.append((era.label, len(cumulative)))
lines += ["Actions unlocked so far, by era (the menu a tribe sees is a subset of this: gates and filters below remove actions that cannot work right now): "
          + ", ".join(f"{label} {n}" for label, n in sizes) + ".", ""]

lines += ["## Menu sets and locks", "",
          "Some rules replace the menu with a fixed set of actions. They are mechanics, not nudges (`docs/NUDGE-AUDIT.md`).", ""]
for name, members in named_sets.items():
    lines.append(f"- **{name}**: " + ", ".join(sorted(members)))
lines += ["", "Also removed from the menu without a table entry: an action already tried too often (the repetition guard), an action on cooldown (DMM, "
          "conquest, warehouse upgrade), the material gathers once a build can be paid, and anything a survival crisis or an unfinished wall section "
          "narrows (see `Simulation._prepare_turn`).", ""]

for era in ERAS:
    lines += [f"## {era.label} (`{era.key}`)", ""]
    if not era.unlocks_actions:
        lines += ["No actions.", ""]
        continue
    lines += ["| Action | Gate beyond the era | The action itself requires | Retires when | Other menu rules |", "|---|---|---|---|---|"]
    for action in era.unlocks_actions:
        off = action in config.DISABLED_ACTIONS
        gate = afford.get(action)
        guard = "; ".join(guards(action))
        retire = one_time.get(action, "")
        sets = [name for name, members in named_sets.items() if action in members]
        flines = sorted(filter_lines.get(action, ()))
        other = []
        if sets:
            other.append("in: " + ", ".join(sets))
        if flines:
            other.append("filtered in `_prepare_turn` at line " + ", ".join(str(n) for n in flines[:6]))
        cell_action = f"~~{action}~~ (disabled)" if off else action
        lines.append(f"| {cell_action} | {gate or 'free with the era'} | {guard or '-'} | {('`' + retire + '` set') if retire else '-'} | {'; '.join(other) or '-'} |")
    lines.append("")

lines += ["## Actions that no era lists", ""]
listed = {a for era in ERAS for a in era.unlocks_actions}
extra = sorted(a for a in ACTION_REGISTRY if a not in listed)
lines += [", ".join(extra) or "none", "",
          "These are in the registry but come from somewhere else (for example BUILD_JOINT_CASTLE is added to the menu for two allied top-era tribes).", ""]
open(OUT, "w", encoding="utf-8").write("\n".join(lines))
print(f"wrote {OUT}: {len(lines)} lines, {len(ACTION_REGISTRY)} registered actions, {len(listed)} listed in eras")
