"""Writes the redesigned river into backend/world_hydrology_data.py and the generated hydrology block in frontend/index.html, from scripts/river_design.json.

2026-10-08: the owner drew a new river on a screenshot (a course from the northwest mountains to a junction, a west arm into the lake and an east arm to the sea, with a
field of plain land where the old course ran); it was traced into tiles (scratch tracing, saved as scripts/river_design.json). This replaces scripts/generate_hydrology.py's
output for the river and lake: do not rerun that generator over this. Run by hand:

    python scripts/apply_river_design.py

What it does beyond copying the traced tiles:
  - the river that overlaps the lake body becomes lake (a lake has no drowning hazard);
  - the mouth is extended east through the coastal cliffs/shoals to the first ocean tile, so the river meets the sea and the frontend's waterfall (a river tile with ocean
    directly east) draws, as the old river's mouth did (world.biome_at checks river before the coast band for the same reason);
  - the field tiles (the owner's yellow patch) are written as FIELD_TILES, which both biome functions turn into plains.
"""
import json
import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from backend.world import _coast_boundary_x  # noqa: E402  (the coast functions do not read the hydrology data)

DESIGN = ROOT / "scripts" / "river_design.json"
BACKEND = ROOT / "backend" / "world_hydrology_data.py"
FRONTEND = ROOT / "frontend" / "index.html"
MARKER_START = "// === GENERATED HYDROLOGY DATA START (scripts/generate_hydrology.py, do not hand-edit) ==="
MARKER_END = "// === GENERATED HYDROLOGY DATA END ==="
GRID = 100


def build():
    design = json.loads(DESIGN.read_text(encoding="utf-8"))
    river = {tuple(p) for p in design["river"]}
    lake = {tuple(p) for p in design["lake"]}
    field = {tuple(p) for p in design["field"]}
    river -= lake
    # extend the mouth east to the sea: every row of the easternmost columns runs on to the last tile before the ocean
    east = max(x for x, _ in river)
    rows = sorted({y for x, y in river if x >= east - 1})
    for y in rows:
        x = east
        while x + 1 < _coast_boundary_x(y) and x + 1 < GRID:
            x += 1
            river.add((x, y))
    field -= river | lake
    return frozenset(river), frozenset(lake), frozenset(field)


def write_backend(river, lake, field):
    def fmt(tiles):
        return ",\n    ".join(str(t) for t in sorted(tiles))

    BACKEND.write_text(
        '"""Generated by scripts/apply_river_design.py (the owner\'s traced river, scripts/river_design.json) -- do not hand-edit.\n\n'
        "Baked river/lake tile membership, plus the field of plain land where the old river ran.\n"
        '"""\n\n'
        f"RIVER_TILES = frozenset([\n    {fmt(river)},\n])\n\n"
        f"LAKE_TILES = frozenset([\n    {fmt(lake)},\n])\n\n"
        f"# Ground drawn as a field: plain land (biome_at returns plains here).\n"
        f"FIELD_TILES = frozenset([\n    {fmt(field)},\n])\n",
        encoding="utf-8",
    )


def write_frontend(river, lake, field):
    html = FRONTEND.read_text(encoding="utf-8")
    nl = "\r\n" if "\r\n" in html else "\n"
    start = html.index(MARKER_START)
    end = html.index(MARKER_END) + len(MARKER_END)
    enc = lambda tiles: ", ".join(str(x * GRID + y) for x, y in sorted(tiles))  # noqa: E731
    block = nl.join([MARKER_START,
                     f"const HYDROLOGY_RIVER_TILES = new Set([{enc(river)}]);",
                     f"const HYDROLOGY_LAKE_TILES = new Set([{enc(lake)}]);",
                     f"const HYDROLOGY_FIELD_TILES = new Set([{enc(field)}]);",
                     MARKER_END])
    FRONTEND.write_text(html[:start] + block + html[end:], encoding="utf-8", newline="")


if __name__ == "__main__":
    river, lake, field = build()
    write_backend(river, lake, field)
    write_frontend(river, lake, field)
    print(f"river {len(river)} tiles, lake {len(lake)}, field {len(field)}")
